name: TeX Live

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v $(pwd):/wd -w /wd --rm malteschmitz/texlive:20.10 latexmk -pdf thesis
      - uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: thesis.pdf
      - uses: actions/deploy-pages@v1-beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
